# Generated by Django 2.1.7 on 2019-03-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(default='Unknown Author', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Author')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
    ]
