# Generated by Django 2.1.7 on 2019-03-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='added_at',
            field=models.DateField(),
        ),
    ]
