# Generated by Django 2.1.7 on 2019-03-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(),
        ),
    ]
