# Generated by Django 2.1.7 on 2019-03-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
