# Generated by Django 2.1.7 on 2019-03-14 02:10

import csv
import os.path

from django.db import migrations
from django.conf import settings

def load_initial_books(apps, schema_editor):
    Book = apps.get_model('core', 'Book')
    Category = apps.get_model('core', 'Category')
    Author = apps.get_model('core', 'Author')

    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'initial_books.csv')

    with open(datafile, encoding = "ISO-8859-1") as file:
        reader = csv.DictReader(file)

        for row in reader:
            if row['categories']:
                categories, _ = Category.objects.get_or_create(name=row['categories'])

            if row['author']:
                author, _ = Author.objects.get_or_create(name=row['author'])

            book = Book(
                title = row['title'],
                description = row['description'],
                url = row['url'],         
            )

            book.save()

            book.author.add(author)
            book.categories.add(categories)

            book.save()
            
class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190313_2241'),
    ]

    operations = [
        migrations.RunPython(load_initial_books)
    ]
